"""Phase 5.4 — Report Builder (HTML + PDF).

Assembles coaching text, charts, and data into a self-contained HTML report.
Charts are embedded as base64 data URIs for portability.
"""

import base64
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")


class ReportBuilder:
    """Build the coaching report as HTML (with optional PDF export)."""

    def __init__(self, template_dir: str | None = None):
        self.template_dir = template_dir or TEMPLATE_DIR

    def build_html(
        self,
        coaching_data: dict,
        scores: dict,
        charts: dict,
        metadata: dict,
    ) -> str:
        """Assemble the complete HTML report.

        Args:
            coaching_data: Dict with executive_summary, segment_feedback, practice_plan.
            scores: 6-dimension scores dict.
            charts: Dict mapping chart name to file path.
            metadata: Duration, video path, processing time, etc.

        Returns:
            Complete HTML string.
        """
        css = self._load_css()
        exec_summary = coaching_data.get("executive_summary", "")
        segment_feedback = coaching_data.get("segment_feedback", [])
        practice_plan = coaching_data.get("practice_plan", [])

        # Build score cards
        score_cards_html = self._build_score_cards(scores)

        # Embed charts as base64
        chart_images = {}
        for name, path in (charts or {}).items():
            chart_images[name] = self._image_to_base64(path)

        # Build segment feedback sections
        feedback_html = self._build_feedback_sections(segment_feedback)

        # Build practice plan
        practice_html = self._build_practice_plan(practice_plan)

        # Format metadata
        duration_min = metadata.get("duration_sec", 0) / 60
        processing_sec = metadata.get("processing_time_sec", 0)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Speech Coaching Report</title>
    <style>{css}</style>
</head>
<body>

<div class="header">
    <h1>Speech Coaching Report</h1>
    <p class="subtitle">Duration: {duration_min:.1f} minutes | Generated by AI Public Speaking Assistant</p>
    <div class="score-badge">{scores.get('overall', 0):.0f}</div>
    <p class="subtitle">Overall Score</p>
</div>

<h2>Executive Summary</h2>
<p>{exec_summary}</p>

<h2>Dimension Scores</h2>
{score_cards_html}

{self._chart_section("radar", chart_images, "Score Breakdown")}

<div class="page-break"></div>
<h2>Speech Quality Timeline</h2>
{self._chart_section("heatmap", chart_images, "")}

<h2>Emotion Arc</h2>
{self._chart_section("emotion_arc", chart_images, "")}

<h2>Speech Structure</h2>
{self._chart_section("regime_flow", chart_images, "")}

<div class="page-break"></div>
<h2>Key Moments &amp; Coaching Feedback</h2>
{feedback_html}

<h2>Filler Words</h2>
{self._chart_section("filler_map", chart_images, "")}

<div class="page-break"></div>
<h2>Practice Plan</h2>
<p>Based on your scores, here are 3 exercises to focus on:</p>
{practice_html}

<div class="footer">
    <p>AI Public Speaking Assistant | Processing time: {processing_sec:.0f}s</p>
</div>

</body>
</html>"""

        return html

    def save_html(self, html: str, output_path: str) -> str:
        """Save HTML report to file."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info("Saved HTML report to %s", output_path)
        return output_path

    def save_pdf(self, html: str, output_path: str) -> str | None:
        """Convert HTML to PDF. Returns path or None if unavailable."""
        try:
            from weasyprint import HTML
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            HTML(string=html).write_pdf(output_path)
            logger.info("Saved PDF report to %s", output_path)
            return output_path
        except ImportError:
            logger.info("weasyprint not installed, skipping PDF generation")
        except Exception as e:
            logger.warning("PDF generation failed: %s", e)

        try:
            import pdfkit
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            pdfkit.from_string(html, output_path)
            logger.info("Saved PDF report to %s (pdfkit)", output_path)
            return output_path
        except ImportError:
            logger.info("pdfkit not installed, skipping PDF generation")
        except Exception as e:
            logger.warning("PDF generation with pdfkit failed: %s", e)

        return None

    def build_and_save(
        self,
        coaching_data: dict,
        scores: dict,
        charts: dict,
        metadata: dict,
        output_dir: str,
    ) -> dict:
        """Build and save both HTML and PDF reports.

        Returns:
            Dict with 'html' and 'pdf' paths.
        """
        os.makedirs(output_dir, exist_ok=True)

        html = self.build_html(coaching_data, scores, charts, metadata)

        html_path = os.path.join(output_dir, "speech_report.html")
        self.save_html(html, html_path)

        pdf_path = os.path.join(output_dir, "speech_report.pdf")
        pdf_result = self.save_pdf(html, pdf_path)

        return {"html": html_path, "pdf": pdf_result}

    # ── Internal builders ──────────────────────────────────────────

    def _load_css(self) -> str:
        """Load CSS from template directory."""
        css_path = os.path.join(self.template_dir, "styles.css")
        try:
            with open(css_path, "r") as f:
                return f.read()
        except FileNotFoundError:
            logger.warning("CSS file not found at %s", css_path)
            return "body { font-family: sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }"

    def _build_score_cards(self, scores: dict) -> str:
        """Build HTML for the 6 score cards."""
        dims = {k: v for k, v in scores.items() if k != "overall"}
        if not dims:
            return "<p>No scores available.</p>"

        cards = []
        for dim, value in dims.items():
            label = dim.replace("_", " ").title()
            cards.append(
                f'<div class="score-card">'
                f'<div class="dim-name">{label}</div>'
                f'<div class="dim-score">{value:.0f}</div>'
                f'</div>'
            )

        return f'<div class="scores-grid">{"".join(cards)}</div>'

    def _chart_section(self, name: str, chart_images: dict, title: str) -> str:
        """Build HTML for a chart image section."""
        b64 = chart_images.get(name)
        if not b64:
            return ""

        title_html = f"<h3>{title}</h3>" if title else ""
        return (
            f'{title_html}'
            f'<div class="chart-container">'
            f'<img src="data:image/png;base64,{b64}" alt="{name}">'
            f'</div>'
        )

    def _build_feedback_sections(self, feedback: list[dict]) -> str:
        """Build HTML for per-segment coaching feedback."""
        if not feedback:
            return "<p>No specific coaching moments identified.</p>"

        sections = []
        for item in feedback:
            timestamp = item.get("timestamp", "")
            label = item.get("label", "")
            ftype = item.get("type", "")
            text = item.get("feedback", "")

            sections.append(
                f'<div class="feedback-section">'
                f'<span class="timestamp">{timestamp}</span>'
                f'<span class="feedback-type">{ftype}</span>'
                f'<p><strong>{label}</strong></p>'
                f'<p>{text}</p>'
                f'</div>'
            )

        return "".join(sections)

    def _build_practice_plan(self, plan: list[dict]) -> str:
        """Build HTML for the practice plan."""
        if not plan:
            return "<p>Keep practicing regularly!</p>"

        items = []
        for i, exercise in enumerate(plan, 1):
            title = exercise.get("title", f"Exercise {i}")
            desc = exercise.get("description", "")
            freq = exercise.get("frequency", "")

            items.append(
                f'<div class="practice-item">'
                f'<div class="title">{i}. {title}</div>'
                f'<p>{desc}</p>'
                f'<div class="frequency">{freq}</div>'
                f'</div>'
            )

        return "".join(items)

    @staticmethod
    def _image_to_base64(image_path: str) -> str:
        """Convert an image file to base64 string."""
        try:
            with open(image_path, "rb") as f:
                return base64.b64encode(f.read()).decode("utf-8")
        except (FileNotFoundError, IOError):
            return ""
